version: '3.8'

services:
  shopthaioutfit-db:
    image: mysql:8
    container_name: shopthaioutfit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopthaioutfit_db
      MYSQL_USER: shopthaiuser
      MYSQL_PASSWORD: shopthaipassword
    ports:
      - "3307:3306"
    volumes:
      - shopthaioutfit_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  shopthaioutfit-api:
    build: .
    container_name: shopthaioutfit-api
    depends_on:
      shopthaioutfit-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shopthaioutfit-db:3306/shopthaioutfit_db
      SPRING_DATASOURCE_USERNAME: shopthaiuser
      SPRING_DATASOURCE_PASSWORD: shopthaipassword
    ports:
      - "8080:8080"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shopthaioutfit-phpmyadmin
    restart: always
    depends_on:
      - shopthaioutfit-db
    environment:
      PMA_HOST: shopthaioutfit-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"  # เปิด phpMyAdmin บน port 8081

volumes:
  shopthaioutfit_mysql_data:


